name: smk1c
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  syncfusion_flutter_datepicker: ^20.3.48
  art_sweetalert: ^0.0.5
  ntp: ^2.0.0
  flutter_kronos: ^0.0.2+2
  location: ^4.4.0
  timezone: ^0.9.0
  network_info_plus: ^3.0.1
  datetime_setting: ^2.0.2
  awesome_dialog: ^3.0.2
  connectivity_plus: ^2.3.6
  app_settings: ^4.1.8
  lottie: ^1.4.3
  liquid_progress_indicator: ^0.3.2
  analog_clock: ^0.1.1
  flutter_analog_clock: ^0.1.1
  buttons_tabbar: ^1.3.6
  splashscreen: any
  sizer: ^2.0.15
  google_fonts: ^3.0.1
  quickalert: ^1.0.0
  dot_navigation_bar: ^1.0.1+4
  intl: ^0.17.0
  flutter_session_manager: ^1.0.2
  animated_text_kit: ^4.2.2
  web_smooth_scroll: ^1.0.0
  contained_tab_bar_view: ^0.8.0
  shared_preferences: ^2.0.15
  permission_handler: ^10.2.0
  file_picker: ^5.2.2
  image_picker: ^0.8.6
  firebase_auth: ^4.0.2
  cloud_firestore: ^4.0.2
  cupertino_icons: ^1.0.2
  d_chart: ^0.1.0
  percent_indicator: ^4.2.2
  material_design_icons_flutter: ^5.0.6996
  get: 4.6.5
  firebase_core: 2.1.0
  firebase_storage: ^11.0.2
  convex_bottom_bar: 3.1.0+1
  flutter_udid: 2.0.0
  flutter_localizations: 
    sdk: flutter
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  fonts: 
    - family: PoppinBold
      fonts: 
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: PoppinLight
      fonts: 
        - asset: assets/fonts/Poppins-Light.ttf
    - family: PoppinThin
      fonts: 
        - asset: assets/fonts/Poppins-Thin.ttf
  uses-material-design: true

